# Site settings
title: Remote movement
tagline: By Michael & Adriaan
description: "Blablabla"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://remote.adriaan.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

plugins: ["jekyll-paginate"]

permalink: :title

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
